name: hydro_monitor
description: Dashboard monitoring hidroponik dengan MQTT TLS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  mqtt_client: ^10.1.2
  syncfusion_flutter_charts: ^31.1.21
  fl_chart: ^0.68.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
